### ISSUE TITLE
Cannot connect to router

### ISSUE THREAD

**Issue by 3D-Darryl** [luc-github/esp3d.io#12]
Using ESP32 with attached camera, 3.0 source code downloaded March 25. Cannot connect to either of 2 routers that work fine with ESP8266. On ESP8266 using 2.1.2, the boot delay parameter seemed to cause multiple connect attempts, which helped at one site where the spectrum was crowded. On 3.0 the serial does not show multiple attempts, and reverts to Access Point mode after 15 seconds even though the boot delay is 25.

**Comment by luc-github** [comment]
Please go to https://github.com/luc-github/ESP3D and open ticket there and fill needed informations for issue
