### ISSUE TITLE
M117 notifications on webgui

### ISSUE THREAD

**Issue by Wirepower** [luc-github/esp3d.io#30]
Please use this issue only for esp3d.io web site issue 
for [ESP3D](https://github.com/luc-github/ESP3D) /  [ESP3DLib](https://github.com/luc-github/ESP3DLib) /  [ESP3D-TFT](https://github.com/luc-github/ESP3D-TFT)  /  [ESP3D-WEBUI](https://github.com/luc-github/ESP3D-WEBUI)

Please describe what whould be an enhancement

m117 notifications go to my tft, be god to have them on webgui as well?

**Comment by luc-github** [comment]
Please open question on right github as mentionned in message
