### ISSUE TITLE
Home assistant notification documentation is unclear

### ISSUE THREAD

**Issue by johnkiniston** [luc-github/esp3d.io#34]
The page at https://esp3d.io/esp3d/v3.x/documentation/notifications/home-assistant/index.html is unclear about how to configure the token in esp3d.

I've gone into Settings > Notifications and there is no HomeAssistant option there.

Additionally the page intially starts talking about how Line is a home automation platform but it links to the Home Assistant page.

**Comment by luc-github** [comment]
what version of ESP3D and webUI are you using ? this feature has been recently added

**Comment by luc-github** [comment]
Typo fixed - thank you for raising it  - I will push the fix online in few min
