### ISSUE TITLE
Не видит SD card

### ISSUE THREAD

**Issue by Sergey3112** [luc-github/esp3d.io#40]
Please use this issue only for esp3d.io web site issue 
for [ESP3D](https://github.com/luc-github/ESP3D) /  [ESP3DLib](https://github.com/luc-github/ESP3DLib) /  [ESP3D-TFT](https://github.com/luc-github/ESP3D-TFT)  /  [ESP3D-WEBUI](https://github.com/luc-github/ESP3D-WEBUI)

Please describe what part of web site has issue
Board wemos d1 mini & TF shield for wemos d1 mini
I tried options for creating a configuration file in the place where the SD card is registered. in the web form the SD card is included, but there is no information
![17157876802568267862257486444236](https://github.com/luc-github/esp3d.io/assets/169923598/0c049865-bb58-41c7-bb38-a2cb6d8719b5)
![17157877103217027353712937141818](https://github.com/luc-github/esp3d.io/assets/169923598/4d966a13-54dc-4b6c-b56e-215dc622dea7)
![17157880736852933926483755480656](https://github.com/luc-github/esp3d.io/assets/169923598/236cd7cc-d8f7-4516-94fa-128ad71ce1de)
![17157881077414841117786748309399](https://github.com/luc-github/esp3d.io/assets/169923598/2d9fdb83-062a-4edc-adf3-a611c1cc4d0e)
![17157881522092397203514335475120](https://github.com/luc-github/esp3d.io/assets/169923598/283db11f-8344-4d0d-b178-8047304d07f6)
![17157881775117484643310482076158](https://github.com/luc-github/esp3d.io/assets/169923598/73195dce-cccc-4666-93b3-924b2072ec9f)
![17157884137533976907589827095395](https://github.com/luc-github/esp3d.io/assets/169923598/4a63a404-616a-4ad6-be3e-fa4ddb3b9521)

**Comment by luc-github** [comment]
As stated in the top of your ticket because your issue seems the usage and configuration of ESP3D please open issue in https://github.com/luc-github/ESP3D/issues and follow template 

Because it seems you use ESP3D 3.0 and some of your settings looks weird I suggest you to use the configurator : https://luc-github.github.io/ to generate the configuration.h
