### ISSUE TITLE
Send gcode over websocket (8282)

### ISSUE THREAD

**Issue by TFIPS** [luc-github/esp3d.io#46]
Great project! 
The only thing that seems to be missing is the ability to send GCode directly to the printer via WebSocket (8282).

**Comment by luc-github** [comment]
this is implemented in 3.0

**Comment by luc-github** [comment]
check https://esp3d.io/esp3d/v3.x/features/index.html

**Comment by TFIPS** [comment]
I just found out that I need to send a newline for it to be sent. 
Thank you for the great project!
